/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.CaixaCRTL;
import dao.CaixaDAO;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import to.CaixaTO;

/**
 *
 * @author Brenicio
 */
public class AdicionarDinheiro extends javax.swing.JInternalFrame {

    private BigDecimal valorAdicionar;
    CaixaCRTL crtl = new CaixaCRTL();
    Caixa1 c = new Caixa1();

    /**
     * Creates new form AdicionarDinheiro
     * @param parent
     */
    public AdicionarDinheiro(Caixa1 parent) {
        this.c=parent;
        initComponents();
        somenteNumeros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAdicionarDinheiro = new javax.swing.JTextField();

        setTitle("Adicionar Dinheiro");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1433364306_f-check_256.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/sairBOTAO.png"))); // NOI18N
        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("VALOR:");

        txtAdicionarDinheiro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtAdicionarDinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAdicionarDinheiroMouseExited(evt);
            }
        });
        txtAdicionarDinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdicionarDinheiroFocusLost(evt);
            }
        });
        txtAdicionarDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdicionarDinheiroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(txtAdicionarDinheiro))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdicionarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        CaixaTO caixaTo = new CaixaTO();
        caixaTo = crtl.consultar("Aberto");
        if ("Aberto".equals(caixaTo.getStatus())) {
            CaixaDAO dao = new CaixaDAO();
            crtl.getEntradaTo().setCodCaixa(caixaTo.getCodCaixa());
            crtl.getEntradaTo().setCodUsuario(1);
            crtl.getEntradaTo().setDataEntracaC(getDate());
            crtl.getEntradaTo().setDescricao("Entrada manual de dinheiro");
            crtl.getEntradaTo().setHora(getTime());
            crtl.getEntradaTo().setTipoMovimentacao("Suprimento de Caixa");
            crtl.getEntradaTo().setValor(valorAdicionar);
            crtl.AdicionarDinheiro2();
            LimparCampos();
            c.preencherTabela();
        } else {
          JOptionPane.showMessageDialog(null,"O caixa não está aberto! Abra o caixa para que possa adicionar dinheiro.");
        }


    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        c.toFront();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtAdicionarDinheiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdicionarDinheiroMouseExited
        if (!"".equals(txtAdicionarDinheiro.getText())) {
            String sv = txtAdicionarDinheiro.getText();
            String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
            BigDecimal valor = new BigDecimal(vsf);
            valorAdicionar = valor;
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            String valorFormatado = nf.format(valor);
            crtl.somenteNumero2(txtAdicionarDinheiro, valorFormatado.length());
            txtAdicionarDinheiro.setText(valorFormatado);
        }
    }//GEN-LAST:event_txtAdicionarDinheiroMouseExited

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated

    }//GEN-LAST:event_formInternalFrameDeactivated

    private void txtAdicionarDinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdicionarDinheiroFocusLost
         if (!"".equals(txtAdicionarDinheiro.getText())) {
            String sv = txtAdicionarDinheiro.getText();
            String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
            BigDecimal valor = new BigDecimal(vsf);
            valorAdicionar = valor;
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            String valorFormatado = nf.format(valor);
            crtl.somenteNumero2(txtAdicionarDinheiro, valorFormatado.length());
            txtAdicionarDinheiro.setText(valorFormatado);
        }
    }//GEN-LAST:event_txtAdicionarDinheiroFocusLost

    private void txtAdicionarDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdicionarDinheiroKeyPressed
        if ("".equals(txtAdicionarDinheiro.getText())) {
            crtl.somenteNumero2(txtAdicionarDinheiro, 10);
        }
    }//GEN-LAST:event_txtAdicionarDinheiroKeyPressed
    private String getDate() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private String getTime() {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private void LimparCampos() {
        txtAdicionarDinheiro.setText("");
    }

    private void somenteNumeros() {
        crtl.somenteNumero(txtAdicionarDinheiro, 40);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAdicionarDinheiro;
    // End of variables declaration//GEN-END:variables
}
