/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.CaixaCRTL;
import dao.CaixaDAO;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.TableMODEL;
import to.CaixaTO;
import to.EntradaCaixaTO;
import to.ProdutoDetalheTO;
import to.SaidaCaixaTO;
import to.ServicoDetalheTO;

/**
 *
 * @author suporte
 */
public class Caixa1 extends javax.swing.JInternalFrame {

    CaixaCRTL crtl = new CaixaCRTL();
    int codentrada = 0;
    String tipoUsu = "";
    ArrayList<ProdutoDetalheTO> prodA = new ArrayList();
    ArrayList<ServicoDetalheTO> servA = new ArrayList();

    /**
     * Creates new form Caixa1
     */
    public Caixa1() {
        initComponents();
        preencherTabela();
    }

    public Caixa1(String tipoUsu) {
        initComponents();
        this.tipoUsu = tipoUsu;
        if (tipoUsu.equals("Recepcionista")) {
            btnAbrirCaixa.setEnabled(false);
            btnAdicionar.setEnabled(false);
            btnComprovante.setEnabled(false);
            btnFecharCaixa.setEnabled(false);
            btnRetirar.setEnabled(false);
        }
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetirar = new javax.swing.JButton();
        btnComprovante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCaixa = new javax.swing.JTable();
        btnAbrirCaixa = new javax.swing.JButton();
        btnObs = new javax.swing.JButton();
        btnFecharCaixa = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaTotal = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaProduto = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePoduto = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableServico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextATotal = new javax.swing.JTextArea();
        txtStatus = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Caixa");
        setPreferredSize(new java.awt.Dimension(1009, 559));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/retirar dinherio.png"))); // NOI18N
        btnRetirar.setText("Retirar Dinheiro");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnComprovante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/total1.png"))); // NOI18N
        btnComprovante.setText("Imprimir Comprovante");
        btnComprovante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprovanteActionPerformed(evt);
            }
        });

        jTableCaixa.setAutoCreateRowSorter(true);
        jTableCaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jTableCaixa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTableCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Nome", "Descrição", "Hora", "Tipo", "Valor", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCaixa.setToolTipText("");
        jTableCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCaixaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableCaixaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCaixa);
        if (jTableCaixa.getColumnModel().getColumnCount() > 0) {
            jTableCaixa.getColumnModel().getColumn(0).setResizable(false);
            jTableCaixa.getColumnModel().getColumn(1).setResizable(false);
            jTableCaixa.getColumnModel().getColumn(2).setResizable(false);
            jTableCaixa.getColumnModel().getColumn(3).setResizable(false);
            jTableCaixa.getColumnModel().getColumn(4).setResizable(false);
            jTableCaixa.getColumnModel().getColumn(5).setResizable(false);
            jTableCaixa.getColumnModel().getColumn(6).setResizable(false);
        }

        btnAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Abrir caixa 32x32 (2).png"))); // NOI18N
        btnAbrirCaixa.setText("Abrir Caixa");
        btnAbrirCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirCaixaMouseClicked(evt);
            }
        });
        btnAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCaixaActionPerformed(evt);
            }
        });

        btnObs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/obs.png"))); // NOI18N
        btnObs.setText("Observação");
        btnObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObsActionPerformed(evt);
            }
        });

        btnFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/abrir caixa 32x32.png"))); // NOI18N
        btnFecharCaixa.setText("Fechar Caixa");
        btnFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCaixaActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/dinheiro.png"))); // NOI18N
        btnAdicionar.setText("Adicionar Dinheiro");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/atualizar.png"))); // NOI18N
        jButton8.setText("Atualizar Tabela");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextAreaTotal.setColumns(20);
        jTextAreaTotal.setRows(5);
        jScrollPane3.setViewportView(jTextAreaTotal);

        jTextAreaProduto.setColumns(20);
        jTextAreaProduto.setRows(5);
        jScrollPane4.setViewportView(jTextAreaProduto);

        jTablePoduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTablePoduto);

        jTableServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableServico);

        jTextATotal.setColumns(20);
        jTextATotal.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        jTextATotal.setForeground(new java.awt.Color(204, 0, 0));
        jTextATotal.setRows(5);
        jScrollPane2.setViewportView(jTextATotal);

        txtStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6)
                                    .addComponent(jScrollPane2))
                                .addGap(67, 67, 67)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprovante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObs, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addGap(27, 27, 27)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnComprovante, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnObs, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        setBounds(0, 0, 1366, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        RetirarDinheiro rt = new RetirarDinheiro(this);
        MenuPrincipal.getPainel().add(rt);
        rt.setVisible(true);
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCaixaActionPerformed

        CaixaTO caixa = new CaixaTO();
        caixa = crtl.valorTotal();
        if (caixa.getSaldoTotal() == null) {
            crtl.getSaidaTo().setValor(BigDecimal.valueOf(0));
            crtl.getSaidaTo().setDatasaidac(getDate());
            crtl.getSaidaTo().setHorasaidac(getTime());
            crtl.getSaidaTo().setDescricao("Retirada manual de dinheiro");
            crtl.getSaidaTo().setTipoMovimentacao("Sangria de Caixa");
            crtl.getSaidaTo().setCodUsuario(1);
            try {
                crtl.alterarSaidaCaixa();
            } catch (Exception ex) {
                Logger.getLogger(Caixa1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        FecharCaixa fc = new FecharCaixa(this);
        MenuPrincipal.getPainel().add(fc);
        fc.setVisible(true);
    }//GEN-LAST:event_btnFecharCaixaActionPerformed

    private void btnObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObsActionPerformed
        Observacoes1 f2 = new Observacoes1();
        MenuPrincipal.getPainel().add(f2);
        f2.setVisible(true);
    }//GEN-LAST:event_btnObsActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        AdicionarDinheiro ad = new AdicionarDinheiro(this);
        MenuPrincipal.getPainel().add(ad);
        ad.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCaixaActionPerformed
        AbrirCaixa1 caixa = new AbrirCaixa1(this);
        MenuPrincipal.getPainel().add(caixa);
        caixa.setVisible(true);

    }//GEN-LAST:event_btnAbrirCaixaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if (tipoUsu.equals("Recepcionista")) {
            btnFecharCaixa.setEnabled(false);
        } else {
            CaixaCRTL crtl = new CaixaCRTL();
            CaixaTO caixaTo = crtl.consultar("Aberto");
            if ("Aberto".equals(caixaTo.getStatus())) {
                btnAbrirCaixa.setEnabled(false);
                btnFecharCaixa.setEnabled(true);
                btnObs.setEnabled(true);
                txtStatus.setText("ABERTO");
                txtStatus.setForeground(Color.blue);
            } else {
                btnAbrirCaixa.setEnabled(true);
                btnFecharCaixa.setEnabled(false);
                btnObs.setEnabled(false);
                txtStatus.setText("FECHADO");
                txtStatus.setForeground(Color.red);
            }
            preencherTabela();
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void btnAbrirCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirCaixaMouseClicked
        if (btnAbrirCaixa.isEnabled() == false) {
            JOptionPane.showMessageDialog(null, "Já existe um caixa em aberto! Feche o caixa atual para abrir outro.");
        }
    }//GEN-LAST:event_btnAbrirCaixaMouseClicked

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated

    }//GEN-LAST:event_formInternalFrameDeactivated

    private void jTableCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCaixaMouseClicked


    }//GEN-LAST:event_jTableCaixaMouseClicked

    private void btnComprovanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprovanteActionPerformed
//        int linha = jTableCaixa.getSelectedRow();
//        RelatorioComprovante comprovante = new RelatorioComprovante();
//        if (linha != -1) {
//            JOptionPane.showMessageDialog(null, jTableCaixa.getModel().getValueAt(linha, 4).toString());
//            if (jTableCaixa.getModel().getValueAt(linha, 4).toString().equals("Venda")) {
//                codentrada = Integer.parseInt(jTableCaixa.getModel().getValueAt(linha, 6).toString());
//                comprovante.EmitirCupom(codentrada);
//            } else {
//                JOptionPane.showMessageDialog(null, "Selecione uma venda para imprimir o comprovante!");
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Nenhuma venda foi selecionada!");
//        }
    }//GEN-LAST:event_btnComprovanteActionPerformed

    @SuppressWarnings("empty-statement")
    private void jTableCaixaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCaixaMousePressed
        PreencherTabelasDetalhe();
    }//GEN-LAST:event_jTableCaixaMousePressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        preencherTabela();
        Atualizar();
    }//GEN-LAST:event_jButton8ActionPerformed
    public void preencherTabela() {
        CaixaCRTL caixaCRTL = new CaixaCRTL();
        //  ArrayList<CaixaTO> dados = new ArrayList();
        ArrayList<EntradaCaixaTO> entrada = new ArrayList();
        ArrayList<SaidaCaixaTO> saida = new ArrayList();
        ArrayList dados1 = new ArrayList();
        entrada = caixaCRTL.consultarTodosCli();
        saida = caixaCRTL.consultarTodosSaida();
        int i = 0;
        while (i < entrada.size()) {
            String valor = "";
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            valor = nf.format(entrada.get(i).getTotalVenda().doubleValue());
            dados1.add(new Object[]{entrada.get(i).getNomeCliente(), valor, entrada.get(i).getHora(), entrada.get(i).getTipoMovimentacao(), "", entrada.get(i).getDataEntracaC(), entrada.get(i).getCodcliente()});
            i++;
        }
        i = 0;
        while (i < saida.size()) {
            String valor = "";
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            valor = nf.format(saida.get(i).getValor());
            dados1.add(new Object[]{"Sangria de Caixa", valor, saida.get(i).getHorasaidac(), saida.get(i).getTipoMovimentacao(), saida.get(i).getDescricao(), saida.get(i).getDatasaidac(), saida.get(i).getCodSaidaCaixa()});
            i++;
        }
        String[] Colunas = new String[]{"Nome", "Total", "Hora", "Tipo", "Descr.", "Data", "Codigo"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCaixa.setModel(modelo);
        //  jTableCaixa.getRowSorter().toggleSortOrder(3);
        //jTableCaixa.getRowSorter().toggleSortOrder(3);

        jTableCaixa.getColumnModel().getColumn(0).setPreferredWidth(300);
        jTableCaixa.getColumnModel().getColumn(0).setMaxWidth(300);
        jTableCaixa.getColumnModel().getColumn(0).setMinWidth(300);
        jTableCaixa.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableCaixa.getColumnModel().getColumn(1).setMaxWidth(120);
        jTableCaixa.getColumnModel().getColumn(1).setMinWidth(120);
        jTableCaixa.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCaixa.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCaixa.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCaixa.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCaixa.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCaixa.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCaixa.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCaixa.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCaixa.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCaixa.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCaixa.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCaixa.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCaixa.getColumnModel().getColumn(6).setPreferredWidth(-1);
        jTableCaixa.getColumnModel().getColumn(6).setMaxWidth(-1);
        jTableCaixa.getColumnModel().getColumn(6).setMinWidth(-1);
        jTableCaixa.getTableHeader().setReorderingAllowed(false);
        jTableCaixa.setAutoResizeMode(jTableCaixa.AUTO_RESIZE_OFF);

    }

    public void Atualizar() {
        CaixaCRTL crtl = new CaixaCRTL();
        CaixaTO caixaTo = crtl.consultar("Aberto");
        if ("Aberto".equals(caixaTo.getStatus())) {
            btnAbrirCaixa.setEnabled(false);
            btnFecharCaixa.setEnabled(true);
            btnObs.setEnabled(true);
            txtStatus.setText("ABERTO");
            txtStatus.setForeground(Color.blue);
        } else {
            btnAbrirCaixa.setEnabled(true);
            btnFecharCaixa.setEnabled(false);
            btnObs.setEnabled(false);
            txtStatus.setText("FECHADO");
            txtStatus.setForeground(Color.red);
        }
        preencherTabela();

    }

    private String getDate() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private String getTime() {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);
    }

    public void PreencherTabelasDetalhe() {
        int i = jTableCaixa.getSelectedRow();
        //JOptionPane.showMessageDialog(null, jTableCaixa.getModel().getValueAt(i, 3).toString());

        int codcliente = Integer.parseInt(jTableCaixa.getModel().getValueAt(i, 6).toString());
        prodA = crtl.ProdutoDetalhe(codcliente);
        servA = crtl.ServicoDetalhe(codcliente);
        Double totalProd = 0.0;
        Double totalServ = 0.0;
        ArrayList dados = new ArrayList();
        ArrayList dados2 = new ArrayList();
        int t = 0;
        while (t < prodA.size()) {
            String valor = "";
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
                //BigDecimal total = new BigDecimal(0.0);
            //totalProd = totalProd + (total.add(prodA.get(t).getTotalvenda())).doubleValue();
            valor = nf.format(prodA.get(t).getValorvenda().doubleValue());
            dados.add(new Object[]{prodA.get(t).getDescricaoprod(), valor, prodA.get(t).getQtdeven(), prodA.get(t).getCliente()});
            t++;
        }
        t = 0;
        while (t < servA.size()) {
            String valor = "";
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            valor = nf.format(servA.get(t).getValorvenda().doubleValue());
               // BigDecimal total = new BigDecimal(0.0);
            // totalServ = totalServ + (total.add(servA.get(t).getTotalven())).doubleValue();
            dados2.add(new Object[]{servA.get(t).getDescricaoserv(), valor, servA.get(t).getNomefunc(), servA.get(t).getCliente()});
            t++;
        }
        String[] ColunasServ = new String[]{"Serviço", "Preço", "Quem realizou ?", "Cliente"};
        String[] ColunasProd = new String[]{"Produto", "Preço", "Quantidade", "Cliente"};

        TableMODEL modelo = new TableMODEL(dados, ColunasProd);
        jTablePoduto.setModel(modelo);

        TableMODEL modelo2 = new TableMODEL(dados2, ColunasServ);
        jTableServico.setModel(modelo2);

        String total = "";
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        //Double totalFinal = totalProd + totalServ;
        total = jTableCaixa.getModel().getValueAt(jTableCaixa.getSelectedRow(), 1).toString();
        jTextATotal.setText("VALOR A SER COBRADO: " + total);

        jTablePoduto.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTablePoduto.getColumnModel().getColumn(0).setMaxWidth(180);
        jTablePoduto.getColumnModel().getColumn(0).setMinWidth(180);
        jTableServico.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTableServico.getColumnModel().getColumn(0).setMaxWidth(180);
        jTableServico.getColumnModel().getColumn(0).setMinWidth(180);
//        jTableCaixa.getColumnModel().getColumn(1).setPreferredWidth(385);
//        jTableCaixa.getColumnModel().getColumn(1).setMaxWidth(200);
//        jTableCaixa.getColumnModel().getColumn(1).setMinWidth(200);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirCaixa;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnComprovante;
    private javax.swing.JButton btnFecharCaixa;
    private javax.swing.JButton btnObs;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jTableCaixa;
    private javax.swing.JTable jTablePoduto;
    private javax.swing.JTable jTableServico;
    private javax.swing.JTextArea jTextATotal;
    private javax.swing.JTextArea jTextAreaProduto;
    private javax.swing.JTextArea jTextAreaTotal;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
