/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.PagamentoCRTL;
import java.util.ArrayList;
import model.TableMODEL;
import to.PagamentoTO;

/**
 *
 * @author Brenicio
 */
public class ConsultarFormaPag extends javax.swing.JDialog {

    PagamentoCRTL crtl = new PagamentoCRTL();
    public static FormasDePagamento1 fp;
    public static FormasDePagamento2 fpProd;
    String tela = "";

    /**
     * Creates new form ConsultarFormaPag
     */
    public ConsultarFormaPag(FormasDePagamento1 parent, boolean modal) {
        this.fp = parent;
        this.setModal(true);
        initComponents();
        setLocationRelativeTo(fp);
        preencherTabela();
    }

    public ConsultarFormaPag(FormasDePagamento2 parent, boolean modal, String TelaSelecionada) {
        this.fpProd = parent;
        this.tela = TelaSelecionada;
        this.setModal(true);
        initComponents();
        setLocationRelativeTo(fpProd);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbOpcao = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFpagamento = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbOpcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Formas de Pagamento", "Tipo de Pagamento", "Quantidade de Parcelas" }));

        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/visualizar_1.png"))); // NOI18N
        jButton1.setText("Pesquisar");

        jTableFpagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableFpagamento);

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/ok 24x24.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/excluir 24x24.png"))); // NOI18N
        btnCancelar.setText("cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSelecionar)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked
        if (cbOpcao.getSelectedIndex() == 0) {
            Maiuscula();
        } else {
            somenteNumero();
        }
    }//GEN-LAST:event_txtPesquisaMouseClicked

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        if (cbOpcao.getSelectedIndex() == 0) {
            preencherTabela2();
        } else {
            preencherTabela3();
        }

        if (txtPesquisa.getText().equalsIgnoreCase("")) {
            preencherTabela();
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int linha = jTableFpagamento.getSelectedRow();
        crtl.getPagamentoTo().setDescpagamento(jTableFpagamento.getValueAt(linha, 1).toString());
        crtl.getPagamentoTo().setCodformapagamento(Integer.parseInt(jTableFpagamento.getModel().getValueAt(linha, 0).toString()));
        crtl.getPagamentoTo().setTipopagamento(jTableFpagamento.getValueAt(linha, 2).toString());
        crtl.getPagamentoTo().setQtdparcela(Integer.parseInt(jTableFpagamento.getValueAt(linha, 3).toString()));

        if (tela.equals("vendaProd")) {
            fpProd.recebendo(crtl.getPagamentoTo());
            this.dispose();
            fpProd.setVisible(true);
        } else {
            fp.recebendo(crtl.getPagamentoTo());
            this.dispose();
            fp.setVisible(true);
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    public void preencherTabela() {
        PagamentoCRTL pagCrtl = new PagamentoCRTL();
        ArrayList<PagamentoTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();
        dados = pagCrtl.consultarTodos();
        int i = 0;
        while (i < dados.size()) {
            dados1.add(new Object[]{dados.get(i).getCodformapagamento(), dados.get(i).getDescpagamento(), dados.get(i).getTipopagamento(), dados.get(i).getQtdparcela()});
            i++;

        }
        String[] Colunas = new String[]{"Codigo", "Descricao", "Tipo", "Parcelas"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableFpagamento.setModel(modelo);
        jTableFpagamento.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFpagamento.getTableHeader().setReorderingAllowed(false);
        jTableFpagamento.setAutoResizeMode(jTableFpagamento.AUTO_RESIZE_OFF);
    }

    public void preencherTabela2() {
        PagamentoTO pagTo = new PagamentoTO();
        PagamentoCRTL pagCrtl = new PagamentoCRTL();
        ArrayList<PagamentoTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();

        dados = pagCrtl.consultarTodosP(txtPesquisa.getText());

        int i = 0;
        while (i < dados.size()) {
            dados1.add(new Object[]{dados.get(i).getCodformapagamento(), dados.get(i).getDescpagamento(), dados.get(i).getTipopagamento(), dados.get(i).getQtdparcela()});
            i++;

        }
        String[] Colunas = new String[]{"Codigo", "Descricao", "Tipo", "Parcelas"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableFpagamento.setModel(modelo);
        jTableFpagamento.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFpagamento.getTableHeader().setReorderingAllowed(false);
        jTableFpagamento.setAutoResizeMode(jTableFpagamento.AUTO_RESIZE_OFF);
    }

    public void preencherTabela3() {

        PagamentoTO pagTo = new PagamentoTO();
        PagamentoCRTL pagCrtl = new PagamentoCRTL();
        ArrayList dados1 = new ArrayList();

        pagTo = pagCrtl.consultarID(Integer.parseInt(txtPesquisa.getText()));

        dados1.add(new Object[]{pagTo.getCodformapagamento(), pagTo.getDescpagamento(), pagTo.getTipopagamento(), pagTo.getQtdparcela(),});

        String[] Colunas = new String[]{"Codigo", "Descricao", "Tipo", "Parcelas"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableFpagamento.setModel(modelo);
        jTableFpagamento.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFpagamento.getTableHeader().setReorderingAllowed(false);
        jTableFpagamento.setAutoResizeMode(jTableFpagamento.AUTO_RESIZE_OFF);

    }

    public void Maiuscula() {
        crtl.Maiuscula(txtPesquisa);
    }

    public void somenteNumero() {
        crtl.somenteNumero(txtPesquisa, 4);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFormaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFormaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFormaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFormaPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarFormaPag dialog = new ConsultarFormaPag(fp, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox cbOpcao;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFpagamento;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
