/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.PessoasCRTL;
import model.TableMODEL;
import java.util.ArrayList;
import java.util.Iterator;
import to.FuncionarioTO;

/**
 *
 * @author Brenicio
 */
public class ConsultarFuncionario extends javax.swing.JInternalFrame {

    PessoasCRTL funcCrtl = new PessoasCRTL();
    Iterator ito;

    /**
     * Creates new form ConsultarFuncionario1
     */
    public ConsultarFuncionario() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();

        setTitle("Consultar Funcionario");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/visualizar.png"))); // NOI18N
        jButton1.setText("Pesquisar");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/ok 24x24.png"))); // NOI18N
        jButton4.setText("Selecionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/excluir 24x24.png"))); // NOI18N
        jButton5.setText("cancelar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome Funcionário", "Matricula" }));

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableFuncionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(450, 130, 434, 316);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed
    private void preencherTabela() {
        ArrayList<FuncionarioTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();
        ito = funcCrtl.consultarTodos("funcionario").iterator();
        while (ito.hasNext()) {
            dados.add((FuncionarioTO) ito.next());
        }
        int i = 0;
        while (i < dados.size()) {
            dados1.add(new Object[]{dados.get(i).getMatricula(), dados.get(i).getNome(), dados.get(i).getCargo(), dados.get(i).getRg(), dados.get(i).getCpf(), dados.get(i).getCelular(), dados.get(i).getTelefone(), dados.get(i).getEmail(), dados.get(i).getEndereco(), dados.get(i).getCidade(), dados.get(i).getCep(), dados.get(i).getSexo(), dados.get(i).getTelefoneRecado(), dados.get(i).getCts(), dados.get(i).getSerie(), dados.get(i).getDatanasc()});
            i++;
        }
        String[] Colunas = new String[]{"Matricula", "Nome", "Cargo", "RG", "CPF", "Celular", "Telefone", "Email", "Endereço", "Cidade", "Cep", "Sexo", "TelefoneRecado", "CTPS", "Serie", "DataNasc"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableFuncionarios.setModel(modelo);

        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableFuncionarios.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableFuncionarios.getColumnModel().getColumn(0).setMinWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(1).setMinWidth(600);
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(2).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(3).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(4).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(5).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(6).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(7).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(8).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(9).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(10).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(11).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(12).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(13).setMinWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(14).setMinWidth(200);

        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
