/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.PessoasCRTL;
import dao.ClienteDAO;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import model.Mascara;
import model.TableMODEL;
import to.ClienteTO;

/**
 *
 * @author brenicio
 */
public class ConsultarCliente extends javax.swing.JInternalFrame {

    PessoasCRTL pessoasCrtl = new PessoasCRTL();
    ManterCliente enviaDados = new ManterCliente();
    public static VendasEfetuadasServico venda = new VendasEfetuadasServico();
    public static VendasEfetuadass vendaProd = new VendasEfetuadass();
    String telaSelecionada = "";
    Iterator ito;
    ClienteTO cliTo = new ClienteTO();

    /**
     * Creates new form ConsultarCliente
     */
    public ConsultarCliente() {
        initComponents();
        preencherTabela();
        MenuPrincipal.getPainel().add(enviaDados);
        enviaDados.setVisible(true);
        GanharFoco(txtPesquisa);
    }

    public ConsultarCliente(VendasEfetuadasServico parent, String tela) {
        this.venda = parent;
        telaSelecionada = tela;
        initComponents();
        preencherTabelaVenda();
        GanharFoco(txtPesquisa);
    }

    public ConsultarCliente(VendasEfetuadass parent, String tela) {
        this.vendaProd = parent;
        telaSelecionada = tela;
        initComponents();
        preencherTabelaVenda();
        GanharFoco(txtPesquisa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbOpcao = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JFormattedTextField();

        setTitle("Consultar Cliente");

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1433364306_f-check_256.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/out 24x24.png"))); // NOI18N
        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbOpcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome Cliente", "Codigo Cliente" }));
        cbOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcaoActionPerformed(evt);
            }
        });

        jTableCliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCliente);

        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbOpcao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(cbOpcao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(200, 0, 1026, 594);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int linha = jTableCliente.getSelectedRow();
        cliTo.setCodCliente(Integer.parseInt(jTableCliente.getValueAt(linha, 0).toString()));
        cliTo.setNome(jTableCliente.getModel().getValueAt(linha, 1).toString());
        cliTo.setEndereco(jTableCliente.getModel().getValueAt(linha, 2).toString());
        cliTo.setCidade(jTableCliente.getModel().getValueAt(linha, 3).toString());
        cliTo.setCpf(jTableCliente.getModel().getValueAt(linha, 4).toString());
        cliTo.setRg(jTableCliente.getModel().getValueAt(linha, 5).toString());
        cliTo.setSexo(jTableCliente.getModel().getValueAt(linha, 6).toString());
        cliTo.setStatusCli(jTableCliente.getModel().getValueAt(linha, 7).toString());
        cliTo.setCelular(jTableCliente.getModel().getValueAt(linha, 8).toString());
        cliTo.setTelefone(jTableCliente.getModel().getValueAt(linha, 9).toString());
        cliTo.setEmail(jTableCliente.getModel().getValueAt(linha, 10).toString());
        cliTo.setBairro(jTableCliente.getModel().getValueAt(linha, 11).toString());
        cliTo.setDataultVisita(jTableCliente.getModel().getValueAt(linha, 12).toString());
        cliTo.setDataCadastro(jTableCliente.getModel().getValueAt(linha, 13).toString());
        cliTo.setCmfotoCli(jTableCliente.getModel().getValueAt(linha, 14).toString());

        if (telaSelecionada.equals("venda")) {
            venda.RecebendoDadosCliente(cliTo);
            this.dispose();
            venda.setVisible(true);
        } else if (telaSelecionada.equals("vendaProd")) {
            vendaProd.ReceberDadosCliente(cliTo);
            this.dispose();
            vendaProd.setVisible(true);
        } else {
            enviaDados.recebendo(cliTo);
            this.dispose();
            enviaDados.setVisible(true);
        }


    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked

        int linha = jTableCliente.getSelectedRow();
        if (cbOpcao.getSelectedIndex() == 0) {
            txtPesquisa.setText(jTableCliente.getValueAt(linha, 1).toString());
        } else {
            txtPesquisa.setText(jTableCliente.getValueAt(linha, 0).toString());
        }
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked
        if (txtPesquisa.getText().equals("")) {
            if (cbOpcao.getSelectedIndex() == 0) {
                Maiuscula(txtPesquisa);
            } else {
                somenteNumero();
            }
        }
    }//GEN-LAST:event_txtPesquisaMouseClicked

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed

    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        if (txtPesquisa.getText().equals("")) {
            if (cbOpcao.getSelectedIndex() == 0) {
                Maiuscula(txtPesquisa);
            } else {
                somenteNumero();
            }
        }
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        if (telaSelecionada.equals("venda")) {
            if (cbOpcao.getSelectedIndex() == 0) {
                
                try {
                    preencherTabelaVenda(txtPesquisa.getText());
                } catch (Exception ex) {
                    Logger.getLogger(ConsultarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else if (cbOpcao.getSelectedIndex() == 1 && !"".equals(txtPesquisa.getText())) {
                try {
                    preencherTabelaVenda(Integer.parseInt(txtPesquisa.getText()));
                } catch (Exception ex) {
                    Logger.getLogger(ConsultarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (txtPesquisa.getText().equalsIgnoreCase("")) {
                try {
                    preencherTabelaVenda();
                } catch (Exception ex) {
                    Logger.getLogger(ConsultarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            if (cbOpcao.getSelectedIndex() == 0) {
                preencherTabela(txtPesquisa.getText());
            } else if (cbOpcao.getSelectedIndex() == 1 && !"".equals(txtPesquisa.getText())) {
                preencherTabela(Integer.parseInt(txtPesquisa.getText()));
            }

            if (txtPesquisa.getText().equalsIgnoreCase("")) {
                preencherTabela();
            }
        }

    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void cbOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcaoActionPerformed
        LimparCampos();
    }//GEN-LAST:event_cbOpcaoActionPerformed
    public void Maiuscula(JFormattedTextField txt) {
        Mascara.Maiuscula(txt);
    }

    public void LimparCampos() {
        txtPesquisa.setText("");
    }

    private void GanharFoco(final JTextField txt) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txt.requestFocusInWindow();
            }
        });
    }

    public void somenteNumero() {
        Mascara.somenteNumero(txtPesquisa, 4);
    }

    private void preencherTabela() {
        ArrayList<ClienteTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();
        ito = pessoasCrtl.ConsultarTodos("Cliente").iterator();
        while (ito.hasNext()) {
            dados.add((ClienteTO) ito.next());
        }

        for (int i = 0; i < dados.size(); i++) {

            dados1.add(new Object[]{dados.get(i).getCodCliente(), dados.get(i).getNome(), dados.get(i).getEndereco(), dados.get(i).getCidade(), dados.get(i).getCpf(),
                dados.get(i).getRg(), dados.get(i).getSexo(), dados.get(i).getStatusCli(), dados.get(i).getCelular(), dados.get(i).getTelefone(), dados.get(i).getEmail(),
                dados.get(i).getBairro(), dados.get(i).getDataultVisita(), dados.get(i).getDataCadastro(), dados.get(i).getCmfotoCli()});
        }

        String[] Colunas = new String[]{"Codigo", "Nome do Cliente", "Endereço", "Cidade", "CPF", "RG", "Sexo", "Status", "Celular", "Telefone", "Email", "Bairro", "Dt Ultima Visita", "Dt Cadastro", "Cm Foto"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCliente.setModel(modelo);

        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCliente.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableCliente.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableCliente.getColumnModel().getColumn(0).setMinWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setMinWidth(600);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMinWidth(200);

        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);

        jTableCliente.getTableHeader().setReorderingAllowed(false);

    }

    private void preencherTabelaVenda() {
        ArrayList<ClienteTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();
        ito = pessoasCrtl.ConsultarTodosAtivosClienteVenda().iterator();

        while (ito.hasNext()) {
            dados.add((ClienteTO) ito.next());
        }

        for (int i = 0; i < dados.size(); i++) {
            dados1.add(new Object[]{dados.get(i).getCodCliente(), dados.get(i).getNome(), dados.get(i).getEndereco(), dados.get(i).getCidade(), dados.get(i).getCpf(),
                dados.get(i).getRg(), dados.get(i).getSexo(), dados.get(i).getStatusCli(), dados.get(i).getCelular(), dados.get(i).getTelefone(), dados.get(i).getEmail(),
                dados.get(i).getBairro(), dados.get(i).getDataultVisita(), dados.get(i).getDataCadastro(), dados.get(i).getCmfotoCli()});
        }

        String[] Colunas = new String[]{"Codigo", "Nome do Cliente", "Endereço", "Cidade", "CPF", "RG", "Sexo", "Status", "Celular", "Telefone", "Email", "Bairro", "Dt Ultima Visita", "Dt Cadastro", "Cm Foto"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCliente.setModel(modelo);

        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCliente.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableCliente.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableCliente.getColumnModel().getColumn(0).setMinWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setMinWidth(600);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMinWidth(200);

        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);

        jTableCliente.getTableHeader().setReorderingAllowed(false);

    }

    public void preencherTabela(String texto) {
        ArrayList<ClienteTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();

        ito = pessoasCrtl.ConsultarTodos(texto, "Cliente").iterator();

        while (ito.hasNext()) {
            dados.add((ClienteTO) ito.next());
        }

        for (int i = 0; i < dados.size(); i++) {
            dados1.add(new Object[]{dados.get(i).getCodCliente(), dados.get(i).getNome(), dados.get(i).getEndereco(), dados.get(i).getCidade(), dados.get(i).getCpf(),
                dados.get(i).getRg(), dados.get(i).getSexo(), dados.get(i).getStatusCli(), dados.get(i).getCelular(), dados.get(i).getTelefone(), dados.get(i).getEmail(),
                dados.get(i).getBairro(), dados.get(i).getDataultVisita(), dados.get(i).getDataCadastro(), dados.get(i).getCmfotoCli()});
        }
        String[] Colunas = new String[]{"Codigo", "Nome do Cliente", "Endereço", "Cidade", "CPF", "RG", "Sexo", "Status", "Celular", "Telefone", "Email", "Bairro", "Dt Ultima Visita", "Dt Cadastro", "Cm Foto"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCliente.setModel(modelo);

        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCliente.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableCliente.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableCliente.getColumnModel().getColumn(0).setMinWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setMinWidth(600);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMinWidth(200);

        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);

        jTableCliente.getTableHeader().setReorderingAllowed(false);
    }

    public void preencherTabelaVenda(String texto) throws Exception {
        ArrayList<ClienteTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();

        ito = pessoasCrtl.ConsultarTodosAtivosClienteVenda(txtPesquisa.getText()).iterator();
        while (ito.hasNext()) {
            dados.add((ClienteTO) ito.next());
        }

        int i = 0;
        while (i < dados.size()) {
            dados1.add(new Object[]{dados.get(i).getCodCliente(), dados.get(i).getNome(), dados.get(i).getEndereco(), dados.get(i).getCidade(), dados.get(i).getCpf(),
                dados.get(i).getRg(), dados.get(i).getSexo(), dados.get(i).getStatusCli(), dados.get(i).getCelular(), dados.get(i).getTelefone(), dados.get(i).getEmail(),
                dados.get(i).getBairro(), dados.get(i).getDataultVisita(), dados.get(i).getDataCadastro(), dados.get(i).getCmfotoCli()});
            i++;
        }
        String[] Colunas = new String[]{"Codigo", "Nome do Cliente", "Endereço", "Cidade", "CPF", "RG", "Sexo", "Status", "Celular", "Telefone", "Email", "Bairro", "Dt Ultima Visita", "Dt Cadastro", "Cm Foto"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCliente.setModel(modelo);

        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCliente.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableCliente.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableCliente.getColumnModel().getColumn(0).setMinWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setMinWidth(600);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMinWidth(200);

        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);

        jTableCliente.getTableHeader().setReorderingAllowed(false);
    }

    public void preencherTabelaVenda(int id) {
        ArrayList dados1 = new ArrayList();

        cliTo = (ClienteTO) pessoasCrtl.ConsultarClienteIDVenda(id);

        dados1.add(new Object[]{cliTo.getCodCliente(), cliTo.getNome(), cliTo.getEndereco(), cliTo.getCidade(), cliTo.getCpf(),
            cliTo.getRg(), cliTo.getSexo(), cliTo.getStatusCli(), cliTo.getCelular(), cliTo.getTelefone(), cliTo.getEmail(),
            cliTo.getBairro(), cliTo.getDataultVisita(), cliTo.getDataCadastro(), cliTo.getCmfotoCli()});

        String[] Colunas = new String[]{"Codigo", "Nome do Cliente", "Endereço", "Cidade", "CPF", "RG", "Sexo", "Status", "Celular", "Telefone", "Email", "Bairro", "Dt Ultima Visita", "Dt Cadastro", "Cm Foto"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCliente.setModel(modelo);

        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCliente.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableCliente.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableCliente.getColumnModel().getColumn(0).setMinWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setMinWidth(600);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMinWidth(200);

        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);

        jTableCliente.getTableHeader().setReorderingAllowed(false);
    }

    public void preencherTabela(int id) { 
        ArrayList dados1 = new ArrayList();

        cliTo = (ClienteTO)pessoasCrtl.Consultar(id,"Cliente");

        dados1.add(new Object[]{cliTo.getCodCliente(), cliTo.getNome(), cliTo.getEndereco(), cliTo.getCidade(), cliTo.getCpf(),
            cliTo.getRg(), cliTo.getSexo(), cliTo.getStatusCli(), cliTo.getCelular(), cliTo.getTelefone(), cliTo.getEmail(),
            cliTo.getBairro(), cliTo.getDataultVisita(), cliTo.getDataCadastro(), cliTo.getCmfotoCli()});

        String[] Colunas = new String[]{"Codigo", "Nome do Cliente", "Endereço", "Cidade", "CPF", "RG", "Sexo", "Status", "Celular", "Telefone", "Email", "Bairro", "Dt Ultima Visita", "Dt Cadastro", "Cm Foto"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableCliente.setModel(modelo);

        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCliente.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableCliente.getColumnModel().getColumn(1).setMaxWidth(600);
        jTableCliente.getColumnModel().getColumn(0).setMinWidth(80);
        jTableCliente.getColumnModel().getColumn(1).setMinWidth(600);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(7).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(8).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(9).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(10).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(11).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(12).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(13).setMinWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMaxWidth(200);
        jTableCliente.getColumnModel().getColumn(14).setMinWidth(200);

        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);

        jTableCliente.getTableHeader().setReorderingAllowed(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox cbOpcao;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JFormattedTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

}
