/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.ProdutoCRTL;
import java.math.BigDecimal;
import java.text.NumberFormat;
import model.TableMODEL;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import to.ProdutoTO;

/**
 *
 * @author kamila
 */
public class ConsultarProduto extends javax.swing.JInternalFrame {

    ManterProduto enviaDados = new ManterProduto();
    VendasEfetuadasServico vendaServ = new VendasEfetuadasServico();
    VendasEfetuadass vendasProd = new VendasEfetuadass();
    ProdutoCRTL prod = new ProdutoCRTL();
    String venda = "";

    /**
     * Creates new form ConsultarProduto
     */
    public ConsultarProduto() {
        initComponents();
        MenuPrincipal.getPainel().add(enviaDados);
        enviaDados.setVisible(true);
        preencherTabela();
    }

    public ConsultarProduto(String Venda, VendasEfetuadasServico vendaServ) {
        initComponents();
        this.venda = Venda;
        this.vendaServ = vendaServ;
        preencherTabela();
    }

    public ConsultarProduto(String Venda, VendasEfetuadass vendaProd) {
        initComponents();
        this.venda = Venda;
        this.vendasProd = vendaProd;
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbOpcao = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consultar produto");

        cbOpcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descrição", "Codigo de Barras" }));

        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableProdutos);

        jTable3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/ok 24x24.png"))); // NOI18N
        jButton4.setText("Selecionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/excluir 24x24.png"))); // NOI18N
        jButton5.setText("cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setBounds(450, 130, 564, 342);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int linha = jTableProdutos.getSelectedRow();
        prod.getProdutoTo().setCodBarra(Integer.parseInt(jTableProdutos.getModel().getValueAt(linha, 1).toString()));
        prod.getProdutoTo().setDescrProd(jTableProdutos.getModel().getValueAt(linha, 2).toString());
        prod.getProdutoTo().setNomeMarca(jTableProdutos.getModel().getValueAt(linha, 3).toString());
        prod.getProdutoTo().setCategoria(jTableProdutos.getModel().getValueAt(linha, 4).toString());
        prod.getProdutoTo().setQtdeProd(Integer.parseInt(jTableProdutos.getModel().getValueAt(linha, 7).toString()));
        //  prod.getProdutoTo().setQtdeEstoque(Integer.parseInt(jTableProdutos.getModel().getValueAt(linha, 8).toString()));
        String sv = (jTableProdutos.getModel().getValueAt(linha, 8).toString()).replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        BigDecimal valLucro = new BigDecimal(sv);
        prod.getProdutoTo().setLucroProd(valLucro.doubleValue());
        sv = (jTableProdutos.getModel().getValueAt(linha, 6).toString()).replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        BigDecimal valCusto = new BigDecimal(sv);
        prod.getProdutoTo().setValorCusto(valCusto.doubleValue());
        sv = (jTableProdutos.getModel().getValueAt(linha, 5).toString()).replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        BigDecimal valVenda = new BigDecimal(sv);
        prod.getProdutoTo().setValorVenda(valVenda.doubleValue());
        prod.getProdutoTo().setCmFoto(jTableProdutos.getModel().getValueAt(linha, 9).toString());
        prod.getProdutoTo().setCodCategoria(Integer.parseInt(jTableProdutos.getModel().getValueAt(linha, 11).toString()));
        prod.getProdutoTo().setCodMarca(Integer.parseInt(jTableProdutos.getModel().getValueAt(linha, 10).toString()));
        prod.getProdutoTo().setCodProd(Integer.parseInt(jTableProdutos.getModel().getValueAt(linha, 0).toString()));

//        if (this.venda.equals("venda")) {
//            try {
//                this.vendaServ.RecebendoDadosProduto(prod.getProdutoTo());
//            } catch (Exception ex) {
//                Logger.getLogger(ConsultarProduto.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            this.dispose();
//            this.vendaServ.setVisible(true);
//
//        } else 
        if (this.venda.equals("VendaProd")) {
            this.vendasProd.RecebendoDadosProduto(prod.getProdutoTo());
            this.dispose();
            this.vendasProd.setVisible(true);
        } else {
            enviaDados.recebendoProduto(prod.getProdutoTo());
            this.dispose();
            enviaDados.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        if (cbOpcao.getSelectedIndex() == 0) {
            preencherTabela2();
        } else {
            preencherTabela3();
        }

        if (txtPesquisa.getText().equalsIgnoreCase("")) {
            preencherTabela();
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked
        if (cbOpcao.getSelectedIndex() == 0) {
            Maiuscula();
        } else {
            somenteNumero();
        }
    }//GEN-LAST:event_txtPesquisaMouseClicked
    public void preencherTabela() {
        ProdutoCRTL usuCRTL = new ProdutoCRTL();
        ArrayList<ProdutoTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();
        dados = usuCRTL.consultarTodos();
        int i = 0;
        while (i < dados.size()) {
            String valVenda = "";
            String valCusto = "";
            String valLucro = "";
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            valVenda = nf.format(BigDecimal.valueOf(dados.get(i).getValorVenda()));
            valCusto = nf.format(BigDecimal.valueOf(dados.get(i).getValorCusto()));
            valLucro = nf.format(BigDecimal.valueOf(dados.get(i).getLucroProd()));
            dados1.add(new Object[]{dados.get(i).getCodProd(), dados.get(i).getCodBarra(), dados.get(i).getDescrProd(), dados.get(i).getNomeMarca(), dados.get(i).getCategoria(), valVenda, valCusto, dados.get(i).getQtdeProd(), valLucro, dados.get(i).getCmFoto(), dados.get(i).getCodMarca(), dados.get(i).getCodCategoria()});
            i++;

        }
        String[] Colunas = new String[]{"Codigo", "Codigo de barras", "Nome", "Marca", "Categoria", "Valor Venda", "Valor Custo", "Quantidade", "Lucro", "Foto", "CodMarca", "CodCategoria"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableProdutos.setModel(modelo);

        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(130);
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(8).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(9).setPreferredWidth(80);

        jTableProdutos.setAutoResizeMode(jTableProdutos.AUTO_RESIZE_OFF);
        jTableProdutos.getColumnModel().getColumn(11).setPreferredWidth(0);
        jTableProdutos.getColumnModel().getColumn(11).setMinWidth(0);
        jTableProdutos.getColumnModel().getColumn(11).setMaxWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setPreferredWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setMinWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setMaxWidth(0);
        //jTableProdutos.getRowSorter().toggleSortOrder(0);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);

    }

    public void preencherTabela2() {
        ProdutoTO prodTo = new ProdutoTO();
        ProdutoCRTL prodCrtl = new ProdutoCRTL();
        ArrayList<ProdutoTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();

        dados = prodCrtl.consultarTodosP(txtPesquisa.getText());

        int i = 0;
        while (i < dados.size()) {
            String valVenda = "";
            String valCusto = "";
            String valLucro = "";
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            valVenda = nf.format(BigDecimal.valueOf(dados.get(i).getValorVenda()));
            valCusto = nf.format(BigDecimal.valueOf(dados.get(i).getValorCusto()));
            valLucro = nf.format(BigDecimal.valueOf(dados.get(i).getLucroProd()));
            dados1.add(new Object[]{dados.get(i).getCodProd(), dados.get(i).getCodBarra(), dados.get(i).getDescrProd(), dados.get(i).getNomeMarca(), dados.get(i).getCategoria(), valVenda, valCusto, dados.get(i).getQtdeProd(), valLucro, dados.get(i).getCmFoto(), dados.get(i).getCodMarca(), dados.get(i).getCodCategoria()});
            i++;

        }
        String[] Colunas = new String[]{"Codigo", "Codigo de barras", "Nome", "Marca", "Categoria", "Valor Venda", "Valor Custo", "Quantidade", "Lucro", "Foto", "CodMarca", "CodCategoria"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableProdutos.setModel(modelo);

        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(130);
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(8).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.setAutoResizeMode(jTableProdutos.AUTO_RESIZE_OFF);
        jTableProdutos.getColumnModel().getColumn(11).setPreferredWidth(0);
        jTableProdutos.getColumnModel().getColumn(11).setMinWidth(0);
        jTableProdutos.getColumnModel().getColumn(11).setMaxWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setPreferredWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setMinWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setMaxWidth(0);
        // jTableProdutos.getRowSorter().toggleSortOrder(2);
    }

    public void preencherTabela3() {

        ProdutoTO prodTo = new ProdutoTO();
        ProdutoCRTL prodCrtl = new ProdutoCRTL();
        ArrayList dados1 = new ArrayList();

        prodTo = prodCrtl.consultarID(Integer.parseInt(txtPesquisa.getText()));

        String valVenda = "";
        String valCusto = "";
        String valLucro = "";
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        valVenda = nf.format(BigDecimal.valueOf(prodTo.getValorVenda()));
        valCusto = nf.format(BigDecimal.valueOf(prodTo.getValorCusto()));
        valLucro = nf.format(BigDecimal.valueOf(prodTo.getLucroProd()));

        dados1.add(new Object[]{prodTo.getCodProd(), prodTo.getCodBarra(), prodTo.getDescrProd(), prodTo.getNomeMarca(), prodTo.getCategoria(), valVenda, valCusto, prodTo.getQtdeProd(), valLucro, prodTo.getCmFoto(), prodTo.getCodMarca(), prodTo.getCodCategoria()});

        String[] Colunas = new String[]{"Codigo", "Codigo de barras", "Nome", "Marca", "Categoria", "Valor Venda", "Valor Custo", "Quantidade", "Lucro", "Foto", "CodMarca", "CodCategoria"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableProdutos.setModel(modelo);

        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(130);
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(8).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(9).setPreferredWidth(80);

        jTableProdutos.setAutoResizeMode(jTableProdutos.AUTO_RESIZE_OFF);
        jTableProdutos.getColumnModel().getColumn(11).setPreferredWidth(0);
        jTableProdutos.getColumnModel().getColumn(11).setMinWidth(0);
        jTableProdutos.getColumnModel().getColumn(11).setMaxWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setPreferredWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setMinWidth(0);
        jTableProdutos.getColumnModel().getColumn(10).setMaxWidth(0);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        // jTableProdutos.getRowSorter().toggleSortOrder(2);

    }

    public void Maiuscula() {
        prod.Maiuscula(txtPesquisa);
    }

    public void somenteNumero() {
        prod.somenteNumero(txtPesquisa, 4);
    }

    public void GanharFoco(final VendasEfetuadasServico vs) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                vs.requestFocus();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOpcao;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
