/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.FuncionarioCRTL;
import java.util.ArrayList;
import model.TableMODEL;
import to.FuncionarioTO;
import to.UsuarioTO;

/**
 *
 * @author Brenicio
 */
public class ConsultarFuncUsu extends javax.swing.JDialog {
ManterFuncionario enviaDados = new ManterFuncionario();
    ManterUsuario enviaDados2 = new ManterUsuario();
    public static ManterUsuario usu;
    FuncionarioTO funcTo = new FuncionarioTO();
    UsuarioTO usuTo = new UsuarioTO();
    FuncionarioCRTL funcCrtl = new FuncionarioCRTL();
    String telaSelecionada;
    /**
     * Creates new form ConsultarFuncUsu
     */
    public ConsultarFuncUsu(ManterUsuario parent, boolean modal) {
        this.usu = parent;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(usu);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbOpcao = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/visualizar.png"))); // NOI18N
        jButton1.setText("Pesquisar");

        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/ok 24x24.png"))); // NOI18N
        jButton4.setText("Selecionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/excluir 24x24.png"))); // NOI18N
        jButton5.setText("cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cbOpcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome Funcionário", "Matricula" }));

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFuncionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked
        if (cbOpcao.getSelectedIndex() == 0) {
            Maiuscula();
        } else {
            somenteNumeros();
        }
    }//GEN-LAST:event_txtPesquisaMouseClicked

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        preencherTabela2();
        if (txtPesquisa.getText().equalsIgnoreCase("")) {
            preencherTabela();
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int linha = jTableFuncionarios.getSelectedRow();
        funcTo.setNome(jTableFuncionarios.getValueAt(linha, 1).toString());
        funcTo.setMatricula(Integer.parseInt(jTableFuncionarios.getModel().getValueAt(linha, 0).toString()));
        funcTo.setCargo(jTableFuncionarios.getModel().getValueAt(linha, 2).toString());
        funcTo.setRg(jTableFuncionarios.getModel().getValueAt(linha, 3).toString());
        funcTo.setCpf(jTableFuncionarios.getModel().getValueAt(linha, 4).toString());
        funcTo.setCelular(jTableFuncionarios.getModel().getValueAt(linha, 5).toString());
        funcTo.setTelefone(jTableFuncionarios.getModel().getValueAt(linha, 6).toString());
        funcTo.setEmail(jTableFuncionarios.getModel().getValueAt(linha, 7).toString());
        funcTo.setEndereco(jTableFuncionarios.getModel().getValueAt(linha, 8).toString());
        funcTo.setCidade(jTableFuncionarios.getModel().getValueAt(linha, 9).toString());
        funcTo.setCep(jTableFuncionarios.getModel().getValueAt(linha, 10).toString());
        funcTo.setSexo(jTableFuncionarios.getModel().getValueAt(linha, 11).toString());
        funcTo.setTelefoneRecado(jTableFuncionarios.getModel().getValueAt(linha, 12).toString());
        funcTo.setCts(jTableFuncionarios.getModel().getValueAt(linha, 13).toString());
        funcTo.setSerie(jTableFuncionarios.getModel().getValueAt(linha, 14).toString());
        funcTo.setDatanasc(jTableFuncionarios.getModel().getValueAt(linha, 15).toString());
        funcTo.setUf(jTableFuncionarios.getModel().getValueAt(linha, 16).toString());
        funcTo.setSetor(jTableFuncionarios.getModel().getValueAt(linha, 17).toString());

      //  if (telaSelecionada.equalsIgnoreCase("usuario")) {
           usu.recebendo(funcTo);
           this.dispose();
            //this.dispose();
          //  enviaDados2.setVisible(true);
     //   } else {
           
      //  }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked

        int linha = jTableFuncionarios.getSelectedRow();
        if (cbOpcao.getSelectedIndex() == 0) {
            txtPesquisa.setText(jTableFuncionarios.getValueAt(linha, 1).toString());
        } else {
            txtPesquisa.setText(jTableFuncionarios.getValueAt(linha, 0).toString());
        }
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    public void preencherTabela() {
        FuncionarioCRTL funcCRTL = new FuncionarioCRTL();
        ArrayList<FuncionarioTO> dados = new ArrayList();
        ArrayList dados1 = new ArrayList();
        dados = funcCRTL.consultarTodos();
        int i = 0;
        while (i < dados.size()) {
            dados1.add(new Object[]{dados.get(i).getMatricula(), dados.get(i).getNome(), dados.get(i).getCargo(), dados.get(i).getRg(), dados.get(i).getCpf(), dados.get(i).getCelular(), dados.get(i).getTelefone(), dados.get(i).getEmail(), dados.get(i).getEndereco(), dados.get(i).getCidade(), dados.get(i).getCep(), dados.get(i).getSexo(), dados.get(i).getTelefoneRecado(), dados.get(i).getCts(), dados.get(i).getSerie(), dados.get(i).getDatanasc(), dados.get(i).getUf(), dados.get(i).getSetor()});
            i++;

        }
        String[] Colunas = new String[]{"Matricula", "Nome", "Cargo", "RG", "CPF", "Celular", "Telefone", "Email", "Endereço",
            "Cidade", "Cep", "Sexo", "TelefoneRecado", "CTPS", "Serie", "DataNasc", "UF", "Setor"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableFuncionarios.setModel(modelo);
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
    }

    public void preencherTabela2() {

        FuncionarioTO funcTo = new FuncionarioTO();
        FuncionarioCRTL funcCRTL = new FuncionarioCRTL();
        if (cbOpcao.getSelectedIndex() == 0) {
            funcTo = funcCRTL.consultar(txtPesquisa.getText());
        } else {
            funcTo = funcCRTL.consultarID(Integer.parseInt(txtPesquisa.getText()));
        }
        ArrayList dados1 = new ArrayList();

        dados1.add(new Object[]{funcTo.getMatricula(), funcTo.getNome(), funcTo.getCargo(), funcTo.getRg(), funcTo.getCpf(), funcTo.getCelular(), funcTo.getTelefone(), funcTo.getEmail(), funcTo.getEndereco(), funcTo.getCidade(),
            funcTo.getCep(), funcTo.getSexo(), funcTo.getTelefoneRecado(), funcTo.getCts(), funcTo.getSerie(), funcTo.getDatanasc(), funcTo.getUf()});

        String[] Colunas = new String[]{"Matricula", "Nome", "Cargo", "RG", "CPF", "Celular", "Telefone", "Email", "Endereço",
            "Cidade", "Cep", "Sexo", "TelefoneRecado", "CTPS", "Serie", "DataNasc", "UF"};

        TableMODEL modelo = new TableMODEL(dados1, Colunas);
        jTableFuncionarios.setModel(modelo);
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);

    }

    public void Maiuscula() {
        funcCrtl.Maiuscula(txtPesquisa);
    }

    public void somenteNumeros() {
        funcCrtl.somenteNumero(txtPesquisa, 4);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarFuncUsu dialog = new ConsultarFuncUsu(usu, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOpcao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JFormattedTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
