/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.CaixaCRTL;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import to.CaixaTO;

/**
 *
 * @author kamila
 */
public class FecharCaixa extends javax.swing.JInternalFrame {

    CaixaCRTL crtl = new CaixaCRTL();
    BigDecimal valorFinal;
    Double faltando;
    BigDecimal valorFalta;
    BigDecimal saldototal;
    Caixa1 caixa = new Caixa1();

    /**
     * Creates new form FecharCaixa
     * @param caixa
     */
    public FecharCaixa(Caixa1 caixa) {
        initComponents();
        this.caixa = caixa;
        formataPreco(txtFinalCaixa);
        formataPreco(txtFaltandoCaixa);
        formataPreco(txtSaldoTotal);
        ValorTotal();
        DesabilitaTextField();
        
        if(!"".equals(txtSaldoTotal.getText())){
            btnFechar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblFaltando = new javax.swing.JLabel();
        txtFinalCaixa = new javax.swing.JTextField();
        txtFaltandoCaixa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoTotal = new javax.swing.JFormattedTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Fechar Caixa");

        lblFaltando.setText("Faltando:");

        txtFinalCaixa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtFinalCaixa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFinalCaixaFocusLost(evt);
            }
        });
        txtFinalCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFinalCaixaMouseExited(evt);
            }
        });
        txtFinalCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalCaixaActionPerformed(evt);
            }
        });
        txtFinalCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFinalCaixaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFinalCaixaKeyReleased(evt);
            }
        });

        txtFaltandoCaixa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtFaltandoCaixa.setForeground(new java.awt.Color(204, 0, 0));
        txtFaltandoCaixa.setCaretColor(new java.awt.Color(204, 0, 0));
        txtFaltandoCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFaltandoCaixaMouseExited(evt);
            }
        });

        jLabel6.setText("Saldo Final do Caixa:");

        jLabel4.setText("Saldo Total:");

        txtSaldoTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtSaldoTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSaldoTotalMouseExited(evt);
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Fechar caixa grande.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFinalCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaltando)
                    .addComponent(txtFaltandoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinalCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFaltando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFaltandoCaixa))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(lblFaltando, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtFinalCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtFaltandoCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtSaldoTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1433364306_f-check_256.png"))); // NOI18N
        btnFechar.setText("Fechar o Caixa");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        CaixaTO caixaTo = new CaixaTO();
        caixaTo = crtl.consultar("Aberto");
        crtl.getCaixaTo().setDtfechamento(getDate());
        crtl.getCaixaTo().setHrfechamento(getTime());
        crtl.getCaixaTo().setValfinal(valorFinal);
        crtl.getCaixaTo().setSaldoTotal(saldototal);
        crtl.getCaixaTo().setFaltando(valorFalta);
        crtl.getCaixaTo().setCodCaixa(caixaTo.getCodCaixa());
        crtl.getCaixaTo().setStatus("Fechado");
        crtl.alterarCaixa();
        this.dispose();
        
//        JOptionPane.showMessageDialog(null, saldototal);
//        JOptionPane.showMessageDialog(null, valorFalta);
        LimparCampos();
        caixa.Atualizar();
        
        if(txtSaldoTotal.getText().equals("")){
            btnFechar.setEnabled(false);
        }

    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtFinalCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFinalCaixaMouseExited
       if (!"".equals(txtFinalCaixa.getText())) {
            String sv = txtFinalCaixa.getText();
            String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
            BigDecimal valor = new BigDecimal(vsf);
            valorFinal = valor;
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            String valorFormatado = nf.format(valor);
            txtFinalCaixa.setText(valorFormatado);

        }
    }//GEN-LAST:event_txtFinalCaixaMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFinalCaixaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFinalCaixaFocusLost
        if (!"".equals(txtFinalCaixa.getText())) {
            String sv = txtFinalCaixa.getText();
            String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
            BigDecimal valor = new BigDecimal(vsf);
            valorFinal = valor;
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            String valorFormatado = nf.format(valor);
            txtFinalCaixa.setText(valorFormatado);
        }
    }//GEN-LAST:event_txtFinalCaixaFocusLost

    private void txtSaldoTotalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSaldoTotalMouseExited


    }//GEN-LAST:event_txtSaldoTotalMouseExited

    private void txtFaltandoCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFaltandoCaixaMouseExited
//        if (!"".equals(txtFaltandoCaixa.getText())) {
//            String sv = txtFaltandoCaixa.getText();
//            String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
//            BigDecimal valor = new BigDecimal(vsf);
//            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
//            String valorFormatado = nf.format(valor);
//            txtFaltandoCaixa.setText(valorFormatado);
//        }
    }//GEN-LAST:event_txtFaltandoCaixaMouseExited

    private void txtFinalCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalCaixaActionPerformed
        
        //txtFaltandoCaixa.setVisible(true);


    }//GEN-LAST:event_txtFinalCaixaActionPerformed

    private void txtFinalCaixaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinalCaixaKeyPressed


    }//GEN-LAST:event_txtFinalCaixaKeyPressed

    private void txtFinalCaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinalCaixaKeyReleased
       if(!"".equals(txtFinalCaixa.getText())){
        String sv = txtFinalCaixa.getText();
        String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        BigDecimal valor = new BigDecimal(vsf);
        String sv2 = txtSaldoTotal.getText();
        String vsf2 = sv2.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        saldototal = new BigDecimal(vsf2);
        faltando = (valor.subtract(saldototal)).doubleValue();

        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorFormatado = nf.format(faltando);

        if (faltando >= 0) {
            txtFaltandoCaixa.setVisible(false);
            lblFaltando.setVisible(false);
        } else if(faltando <0){
            lblFaltando.setVisible(true);
            txtFaltandoCaixa.setVisible(true);
            txtFaltandoCaixa.setEditable(false);
            txtFaltandoCaixa.setText(valorFormatado);
            String falt = txtFaltandoCaixa.getText();
            String falt2 = falt.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
            valorFalta = new BigDecimal(falt2);
        }
       }else{
           txtFaltandoCaixa.setText("");
       }
    }//GEN-LAST:event_txtFinalCaixaKeyReleased

    private String getDate() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private String getTime() {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private void LimparCampos() {
        txtFaltandoCaixa.setText("");
        txtFinalCaixa.setText("");
        txtSaldoTotal.setText("");
    }

    private void formataPreco(JTextField txt) {
        crtl.somenteNumero(txt, 40);
    }

    private void ValorTotal() {
        CaixaTO caixa = new CaixaTO();

        caixa = crtl.valorTotal();
        if (caixa.getSaldoTotal() == null) {
            try {
                caixa = crtl.ValorTotalSomenteCaixa();
            } catch (Exception ex) {
                Logger.getLogger(FecharCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        BigDecimal valor = caixa.getSaldoTotal();
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorFormatado = nf.format(valor);
        txtSaldoTotal.setText(valorFormatado);
    }

    private void DesabilitaTextField() {
        txtSaldoTotal.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel lblFaltando;
    private javax.swing.JTextField txtFaltandoCaixa;
    private javax.swing.JTextField txtFinalCaixa;
    private javax.swing.JFormattedTextField txtSaldoTotal;
    // End of variables declaration//GEN-END:variables
}
