/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.PagamentoCRTL;
import javax.swing.JOptionPane;
import to.PagamentoTO;

/**
 *
 * @author suporte
 */
public class ManterFormaDePagamento1 extends javax.swing.JInternalFrame {
    private Object jframe;
    PagamentoCRTL crtl = new PagamentoCRTL();
    int codigoFp =0;

    /**
     * Creates new form ManterFormaDePagamento1
     */
    public ManterFormaDePagamento1() {
        initComponents();
        desabitilarBotoes();
        desabilitarOpcao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoPag = new javax.swing.JComboBox();
        cbDescPag = new javax.swing.JComboBox();
        jsQtde = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Manter Formas de Pagamento");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Formas de Pagamento:");

        jLabel3.setText("Tipo de Pagamento:");

        jLabel4.setText("Quantidade de Parcelas:");

        cbTipoPag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A VISTA", "A PRAZO" }));
        cbTipoPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPagActionPerformed(evt);
            }
        });

        cbDescPag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DINHEIRO", "CARTAO" }));
        cbDescPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDescPagMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbDescPagMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbDescPagMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbDescPagMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbDescPagMouseReleased(evt);
            }
        });
        cbDescPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDescPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDescPag, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jsQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDescPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbTipoPag, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbDescPag, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jsQtde, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 400, 130));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/consultarBOTAO.png"))); // NOI18N
        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 16, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/addBOTAO.png"))); // NOI18N
        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/alterarBOTAO.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 16, -1, -1));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 15, -1, -1));

        setBounds(450, 130, 432, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       crtl.getPagamentoTo().setDescpagamento(cbDescPag.getSelectedItem().toString());
       crtl.getPagamentoTo().setTipopagamento(cbTipoPag.getSelectedItem().toString());
       crtl.getPagamentoTo().setQtdparcela(Integer.parseInt(jsQtde.getValue().toString()));
       crtl.incluirFormaPagamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar a forma de pagamento: ?", title, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            crtl.getPagamentoTo().setDescpagamento(cbDescPag.getSelectedItem().toString());
            crtl.getPagamentoTo().setQtdparcela(Integer.parseInt(jsQtde.getValue().toString()));
            crtl.getPagamentoTo().setTipopagamento(cbTipoPag.getSelectedItem().toString());
            crtl.getPagamentoTo().setCodformapagamento(codigoFp);
            JOptionPane.showMessageDialog(null, codigoFp);
            crtl.alterarFormaPagamento();
        } else if (resposta == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConsultarFormaPagamento consul = new ConsultarFormaPagamento();
        MenuPrincipal.getPainel().add(consul);
        this.dispose();
        consul.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbDescPagMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDescPagMouseEntered
        
    }//GEN-LAST:event_cbDescPagMouseEntered

    private void cbDescPagMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDescPagMouseExited
       
    }//GEN-LAST:event_cbDescPagMouseExited

    private void cbDescPagMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDescPagMouseReleased
        
    }//GEN-LAST:event_cbDescPagMouseReleased

    private void cbDescPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDescPagMouseClicked
      
    }//GEN-LAST:event_cbDescPagMouseClicked

    private void cbDescPagMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDescPagMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDescPagMousePressed

    private void cbDescPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDescPagActionPerformed
         if(cbDescPag.getSelectedItem().toString().equals("DINHEIRO")){
           jsQtde.setEnabled(false);
           cbTipoPag.removeItem("A PRAZO");
           jsQtde.setValue(0);
       }else{
           jsQtde.setEnabled(true);
           if(cbTipoPag.getItemCount()!=2){
           cbTipoPag.addItem("A PRAZO");
                      
           }
       }
         if(cbTipoPag.getSelectedItem().toString().equals("A VISTA")){
               jsQtde.setEnabled(false);
               jsQtde.setValue(0);
           }
    }//GEN-LAST:event_cbDescPagActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        crtl.excluir(codigoFp);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbTipoPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPagActionPerformed
        if(cbTipoPag.getSelectedItem().toString().equals("A PRAZO")){
               jsQtde.setEnabled(true);
               jsQtde.setValue(0);
           }else{
            jsQtde.setEnabled(false);
            jsQtde.setValue(0);
        }
    }//GEN-LAST:event_cbTipoPagActionPerformed
public void recebendo(PagamentoTO to) {
        codigoFp = to.getCodformapagamento();
        cbDescPag.setSelectedItem(to.getDescpagamento());
        cbTipoPag.setSelectedItem(to.getTipopagamento());
        jsQtde.setValue(to.getQtdparcela());
        habilitarBotoes();
    }
private void habilitarBotoes() {
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
private void desabitilarBotoes() {
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
private void desabilitarOpcao(){
    if(cbDescPag.getSelectedItem().toString().equals("DINHEIRO")){
        cbTipoPag.removeItem("A PRAZO");
        jsQtde.setEnabled(false);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox cbDescPag;
    private javax.swing.JComboBox cbTipoPag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSpinner jsQtde;
    // End of variables declaration//GEN-END:variables
}
