/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.CaixaCRTL;
import dao.ClienteDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import to.CaixaTO;

/**
 *
 * @author kamila
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public int codUsuarioLogado;
    public String tipoUsuarioLogado;
    public LoginFinal login = new LoginFinal(this, true);
    private JInternalFrame vs = new JInternalFrame();
    private JInternalFrame cx = new JInternalFrame();
    private JInternalFrame serv = new JInternalFrame();
    private JInternalFrame cli = new JInternalFrame();
    private JInternalFrame vp = new JInternalFrame();
    private JInternalFrame func = new JInternalFrame();
    private JInternalFrame prod = new JInternalFrame();

    private static MenuPrincipal m;

    public static MenuPrincipal getInstancia() {
        if (m == null) {
            m = new MenuPrincipal();
        }

        return m;
    }

    public static JDesktopPane getPainel() {
        return getInstancia().escritorio1;
    }

    static Object getInstance() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private Object escritorio;

    /**
     * Creates new form MenuPrincipal
     */
    Caixa1 Caixa1;
    ManterUsuario ManterUsuário;
    private Object Internal;

    public MenuPrincipal() {

        initComponents();
        // verificarCaixa();

    }

    public MenuPrincipal(String usuario, int cod, String tipoUsuario) {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnServico = new javax.swing.JButton();
        btnRealizarVenda = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnVendaProd = new javax.swing.JButton();
        escritorio1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnMarca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenuItem();
        menuFpagamento = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuLancamentos = new javax.swing.JMenu();
        menuCaixa = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuFluxoCaixa = new javax.swing.JMenuItem();
        menuVendasEfetuadas = new javax.swing.JMenuItem();
        menuMercadoriaEstoque = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/sair.png"))); // NOI18N
        btnSair.setText("sair");
        btnSair.setMaximumSize(new java.awt.Dimension(139, 57));
        btnSair.setPreferredSize(new java.awt.Dimension(139, 57));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 165, 69));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 11, -1, -1));

        btnServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/cabelereiro.png"))); // NOI18N
        btnServico.setText("Serviço");
        btnServico.setMaximumSize(new java.awt.Dimension(139, 57));
        btnServico.setMinimumSize(new java.awt.Dimension(139, 57));
        btnServico.setPreferredSize(new java.awt.Dimension(139, 57));
        btnServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 165, 69));

        btnRealizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1433995668_shopping cart.png"))); // NOI18N
        btnRealizarVenda.setText("Realizar Venda");
        btnRealizarVenda.setAlignmentY(0.0F);
        btnRealizarVenda.setAutoscrolls(true);
        btnRealizarVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnRealizarVenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRealizarVenda.setMaximumSize(new java.awt.Dimension(139, 57));
        btnRealizarVenda.setMinimumSize(new java.awt.Dimension(139, 57));
        btnRealizarVenda.setPreferredSize(new java.awt.Dimension(139, 57));
        btnRealizarVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 165, 69));

        btnCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Caixa.png"))); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCaixa.setMaximumSize(new java.awt.Dimension(139, 57));
        btnCaixa.setName(""); // NOI18N
        btnCaixa.setPreferredSize(new java.awt.Dimension(139, 57));
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 165, 69));

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/prod 24x24.png"))); // NOI18N
        btnProdutos.setMnemonic('P');
        btnProdutos.setText("Produtos");
        btnProdutos.setToolTipText("Produtos");
        btnProdutos.setHideActionText(true);
        btnProdutos.setMaximumSize(new java.awt.Dimension(139, 57));
        btnProdutos.setMinimumSize(new java.awt.Dimension(139, 57));
        btnProdutos.setPreferredSize(new java.awt.Dimension(139, 57));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 165, 69));

        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/funcionarios.png"))); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFuncionarios.setMaximumSize(new java.awt.Dimension(139, 57));
        btnFuncionarios.setMinimumSize(new java.awt.Dimension(139, 57));
        btnFuncionarios.setPreferredSize(new java.awt.Dimension(139, 57));
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 165, 69));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 1720, 10));

        btnVendaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1433995668_shopping cart.png"))); // NOI18N
        btnVendaProd.setText("Venda Produto");
        btnVendaProd.setMaximumSize(new java.awt.Dimension(139, 57));
        btnVendaProd.setMinimumSize(new java.awt.Dimension(139, 57));
        btnVendaProd.setPreferredSize(new java.awt.Dimension(139, 57));
        btnVendaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnVendaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 165, 69));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fnd3.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout escritorio1Layout = new javax.swing.GroupLayout(escritorio1);
        escritorio1.setLayout(escritorio1Layout);
        escritorio1Layout.setHorizontalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorio1Layout.setVerticalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorio1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(escritorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1720, 620));

        btnMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/clients.png"))); // NOI18N
        btnMarca.setText("Cliente");
        btnMarca.setMaximumSize(new java.awt.Dimension(139, 57));
        btnMarca.setMinimumSize(new java.awt.Dimension(139, 57));
        btnMarca.setPreferredSize(new java.awt.Dimension(139, 57));
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 165, 69));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/azul.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1720, 80));

        jMenuCadastro.setText("Cadastros");

        menuUsuarios.setLabel("Usuários");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(menuUsuarios);

        menuFuncionarios.setLabel("Funcionario");
        menuFuncionarios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuFuncionariosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(menuFuncionarios);

        menuFpagamento.setLabel("Formas de Pagamento");
        menuFpagamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuFpagamentoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuFpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFpagamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(menuFpagamento);

        menuProduto.setLabel("Produto");
        menuProduto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuProdutoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(menuProduto);

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem1);

        jMenuItem2.setText("Serviços");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem2);

        jMenuItem4.setText("Marca");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem4);

        jMenuItem5.setText("Categoria");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem5);

        jMenuBar1.add(jMenuCadastro);

        menuLancamentos.setText("Lançamentos");

        menuCaixa.setText("Caixa");
        menuCaixa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuCaixaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaixaActionPerformed(evt);
            }
        });
        menuLancamentos.add(menuCaixa);

        menuVenda.setText("Realizar Venda");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });
        menuVenda.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuVendaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuLancamentos.add(menuVenda);

        jMenuItem3.setText("Realizar Venda Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuLancamentos.add(jMenuItem3);

        jMenuBar1.add(menuLancamentos);

        menuRelatorios.setText("Relatorios");

        menuFluxoCaixa.setText("Fluxo de Caixa");
        menuFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFluxoCaixaActionPerformed(evt);
            }
        });
        menuFluxoCaixa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuFluxoCaixaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuRelatorios.add(menuFluxoCaixa);

        menuVendasEfetuadas.setText("Vendas Efetuadas");
        menuVendasEfetuadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasEfetuadasActionPerformed(evt);
            }
        });
        menuVendasEfetuadas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuVendasEfetuadasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuRelatorios.add(menuVendasEfetuadas);

        menuMercadoriaEstoque.setText("Mercadoria em Estoque");
        menuMercadoriaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMercadoriaEstoqueActionPerformed(evt);
            }
        });
        menuMercadoriaEstoque.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuMercadoriaEstoqueAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menuRelatorios.add(menuMercadoriaEstoque);

        jMenuBar1.add(menuRelatorios);

        jMenu5.setText("Ajuda");
        jMenuBar1.add(jMenu5);
        jMenuBar1.add(jMenu6);

        jMenu1.setText("Utilitarios");

        jMenuItem6.setText("Desbloquear Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1739, 784));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicoActionPerformed
        ManterServico c = new ManterServico();
        this.escritorio1.add(c);
        c.show();
        serv = this.escritorio1.getSelectedFrame();


    }//GEN-LAST:event_btnServicoActionPerformed

    private void btnRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVendaActionPerformed
        CaixaCRTL crtl = new CaixaCRTL();
        CaixaTO caixaTo = crtl.consultar("Aberto");
        if ("Aberto".equals(caixaTo.getStatus())) {
            btnRealizarVenda.setEnabled(true);
            VendasEfetuadasServico n = new VendasEfetuadasServico(codUsuarioLogado);
            this.escritorio1.add(n);
            n.show();
            vs = this.escritorio1.getSelectedFrame();
        } else {

            JOptionPane.showMessageDialog(null, "E necessário abrir o caixa para realizar uma venda!");
        }


    }//GEN-LAST:event_btnRealizarVendaActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        if (this.escritorio1.getSelectedFrame() != null && this.cx.getClass().getName().equalsIgnoreCase("view.Caixa1")) {
            this.escritorio1.setSelectedFrame(cx);
            cx.toFront();
        } else {
            Caixa1 n = new Caixa1(tipoUsuarioLogado);
            this.escritorio1.add(n);
            n.show();
            cx = this.escritorio1.getSelectedFrame();
        }
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        ManterFuncionario n = new ManterFuncionario();
        this.escritorio1.add(n);
        n.show();
        func = this.escritorio1.getSelectedFrame();


    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnVendaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaProdActionPerformed
        CaixaCRTL crtl = new CaixaCRTL();
        CaixaTO caixaTo = crtl.consultar("Aberto");
        if ("Aberto".equals(caixaTo.getStatus())) {
            VendasEfetuadass vendaprod = new VendasEfetuadass();
            MenuPrincipal.getPainel().add(vendaprod);
            vendaprod.setVisible(true);
            vp = this.escritorio1.getSelectedFrame();

        } else {

            JOptionPane.showMessageDialog(null, "E necessário abrir o caixa para realizar uma venda!");
        }


    }//GEN-LAST:event_btnVendaProdActionPerformed

    private void menuFuncionariosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuFuncionariosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFuncionariosAncestorAdded

    private void menuFpagamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuFpagamentoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFpagamentoAncestorAdded

    private void menuProdutoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuProdutoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProdutoAncestorAdded

    private void menuFluxoCaixaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuFluxoCaixaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFluxoCaixaAncestorAdded

    private void menuVendasEfetuadasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuVendasEfetuadasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVendasEfetuadasAncestorAdded

    private void menuMercadoriaEstoqueAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuMercadoriaEstoqueAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMercadoriaEstoqueAncestorAdded

    private void menuCaixaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuCaixaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCaixaAncestorAdded

    private void menuFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFluxoCaixaActionPerformed
        RelatórioDeFluxoDeCaixa1 n = new RelatórioDeFluxoDeCaixa1();
        this.escritorio1.add(n);
        n.show();

    }//GEN-LAST:event_menuFluxoCaixaActionPerformed

    private void menuVendasEfetuadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasEfetuadasActionPerformed
        RelatórioDeVendasEfetuadas1 n = new RelatórioDeVendasEfetuadas1();
        this.escritorio1.add(n);
        n.show();
    }//GEN-LAST:event_menuVendasEfetuadasActionPerformed

    private void menuMercadoriaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMercadoriaEstoqueActionPerformed
        RelatórioDeEstoqueDeMercadoria1 n = new RelatórioDeEstoqueDeMercadoria1();
        this.escritorio1.add(n);
        n.show();
    }//GEN-LAST:event_menuMercadoriaEstoqueActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.MAXIMIZED_BOTH);
        login.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        ManterUsuario n = new ManterUsuario();
        this.escritorio1.add(n);
        n.show();
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosActionPerformed
        ManterFuncionario n = new ManterFuncionario();
        this.escritorio1.add(n);
        n.show();
    }//GEN-LAST:event_menuFuncionariosActionPerformed

    private void menuFpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFpagamentoActionPerformed
        ManterFormaDePagamento1 n = new ManterFormaDePagamento1();
        this.escritorio1.add(n);
        n.show();
    }//GEN-LAST:event_menuFpagamentoActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed

    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuVendaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuVendaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVendaAncestorAdded

    private void menuCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaixaActionPerformed
        Caixa1 n = new Caixa1();
        this.escritorio1.add(n);
        n.show();
    }//GEN-LAST:event_menuCaixaActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        VendasEfetuadasServico vdserv = new VendasEfetuadasServico();
        this.escritorio1.add(vdserv);
        vdserv.show();
    }//GEN-LAST:event_menuVendaActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed

        ManterProduto prod = new ManterProduto();
        this.escritorio1.add(prod);
        prod.show();
        this.prod = this.escritorio1.getSelectedFrame();

    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed

        ManterCliente n = new ManterCliente();
        this.escritorio1.add(n);
        n.show();
        cli = this.escritorio1.getSelectedFrame();

    }//GEN-LAST:event_btnMarcaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ManterCliente cliente = new ManterCliente();
        this.escritorio1.add(cliente);
        cliente.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ManterServico servico = new ManterServico();
        this.escritorio1.add(servico);
        servico.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VendasEfetuadass venda = new VendasEfetuadass();
        MenuPrincipal.getPainel().add(venda);
        venda.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ManterMarca marca = new ManterMarca();
        MenuPrincipal.getPainel().add(marca);
        marca.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ManterCategoria categoria = new ManterCategoria();
        MenuPrincipal.getPainel().add(categoria);
        categoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            DesbloquearClientes dcli = new DesbloquearClientes();
            MenuPrincipal.getPainel().add(dcli);
            dcli.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    private void verificarCaixa() {
        CaixaCRTL crtl = new CaixaCRTL();
        CaixaTO to = new CaixaTO();
        to = crtl.consultar("Aberto");
        if (to.getStatus().equals("Fechado")) {
            btnRealizarVenda.setEnabled(false);
        }
    }

    public void acesso(int codUsu, String tipoUsu, String usuario) throws Exception {
        ClienteDAO cliDao = new ClienteDAO();     
        
        if (tipoUsu.equals("Gerente")) {
            // btnVendaProd.setEnabled(true);
            menuUsuarios.setEnabled(false);
        } else if (tipoUsu.equals("Recepcionista")) {
            btnVendaProd.setEnabled(false);
            menuUsuarios.setEnabled(false);
            menuProduto.setEnabled(true);
            if(usuario.equals("amanda")){
            btnProdutos.setEnabled(true);
        }else{
                btnProdutos.setEnabled(false);               
            }            
            btnServico.setEnabled(false);
            btnCaixa.setEnabled(true);
            menuCaixa.setEnabled(true);
            menuRelatorios.setEnabled(false);
            menuLancamentos.setEnabled(false);
            btnRealizarVenda.setEnabled(false);
            menuFpagamento.setEnabled(false);
            btnFuncionarios.setEnabled(false);
            jMenuCadastro.setEnabled(false);
            btnVendaProd.setEnabled(true);
        }
        codUsuarioLogado = codUsu;
        tipoUsuarioLogado = tipoUsu;
        this.setTitle("Menu Principal - " + usuario);
        cliDao.VerificarStatus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                getInstancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRealizarVenda;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnServico;
    private javax.swing.JButton btnVendaProd;
    private javax.swing.JDesktopPane escritorio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem menuCaixa;
    private javax.swing.JMenuItem menuFluxoCaixa;
    private javax.swing.JMenuItem menuFpagamento;
    private javax.swing.JMenuItem menuFuncionarios;
    private javax.swing.JMenu menuLancamentos;
    private javax.swing.JMenuItem menuMercadoriaEstoque;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenuItem menuVenda;
    private javax.swing.JMenuItem menuVendasEfetuadas;
    // End of variables declaration//GEN-END:variables

}
