/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import crtl.ProdutoCRTL;
import dao.Conexao;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import to.MarcaTO;

/**
 *
 * @author suporte
 */
public class RelatórioDeEstoqueDeMercadoria1 extends javax.swing.JInternalFrame {

    ProdutoCRTL crtl = new ProdutoCRTL();
    MarcaTO marcaTo = new MarcaTO();
    // MarcaTO marcTo = new MarcaTO();

    /**
     * Creates new form RelatórioDeEstoqueDeMercadoria1
     */
    public RelatórioDeEstoqueDeMercadoria1() {
        initComponents();
        carregarComboMarcas();
//        rbMarca.setSelected(false);
//        rbTodos.setSelected(true);
//        cbMarca.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        rbMarca = new javax.swing.JRadioButton();
        rbTodos = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Relatório Estoque de Mercadoria");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Marca:");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/visualizar.png"))); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rbMarca.setText("Marca");
        rbMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMarcaMouseClicked(evt);
            }
        });

        rbTodos.setText("Todos");
        rbTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTodosMouseClicked(evt);
            }
        });
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(rbMarca)
                                .addGap(70, 70, 70)
                                .addComponent(rbTodos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMarca)
                    .addComponent(rbTodos))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setBounds(450, 130, 425, 233);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        marcaTo = crtl.consultarNOME(cbMarca.getSelectedItem().toString());
        //JOptionPane.showMessageDialog(null, marcaTo.getCodMarca());
        RelatorioEstoque();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMarcaMouseClicked
        if (rbMarca.isSelected() == true) {
            rbTodos.setSelected(false);
            cbMarca.setEnabled(true);
        }

    }//GEN-LAST:event_rbMarcaMouseClicked

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTodosMouseClicked
        if (rbTodos.isSelected() == true) {
            rbMarca.setSelected(false);
            cbMarca.setEnabled(false);
        }
    }//GEN-LAST:event_rbTodosMouseClicked
    private void carregarComboMarcas() {
        ArrayList<String> marcTo;
        marcTo = crtl.consultarMarcas();
        cbMarca.setModel(new DefaultComboBoxModel(marcTo.toArray()));
    }

    private void RelatorioEstoque() {
        try {
            Conexao con = new Conexao();

            if (rbTodos.isSelected() == true) {
                String SQL = "select p.codbarra, p.descricaoprod, p.valorcusto, p.valorvenda, p.quantprod, m.nomemarca ,c.nomecategoria \n"
                        + "from produto p join marca m on p.codmarca=m.codmarca inner join categoria c on c.codcategoria=p.codcat;";
                con.conectaBD();
                ResultSet rs = con.executaConsulta(SQL);
                JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
                HashMap map = new HashMap();
                String arquivo = "C:\\BRK-SISTEMAS\\BRKSISTEMAS-Salão\\BRKSISTEMAStodas4.1\\BRKSISTEMAStodas4\\BRKSISTEMAS-Salão\\Nova Pasta\\relatorioEst.jasper";
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(arquivo);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, jrRS);
                JasperViewer jrviewer = new JasperViewer(jasperPrint, false);
                jrviewer.setVisible(true);
            } else {
                String SQL = "select p.codbarra, p.descricaoprod, p.valorcusto, p.valorvenda, p.quantprod, m.nomemarca ,c.nomecategoria \n"
                        + "from produto p join marca m on p.codmarca=m.codmarca inner join categoria c on c.codcategoria=p.codcat"
                        + " and m.codmarca=" + marcaTo.getCodMarca() + ";";
                con.conectaBD();
                //JOptionPane.showMessageDialog(null, marcaTo.getCodMarca());
                ResultSet rs = con.executaConsulta(SQL);
                JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
                HashMap map = new HashMap();
                String arquivo = "C:\\Users\\Brenicio\\SkyDrive\\Projetos\\BRKSISTEMAS-Salão\\BRKSISTEMAStodas4.1\\BRKSISTEMAStodas4\\BRKSISTEMAS-Salão\\Nova Pasta\\relatorioEst.jasper";
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(arquivo);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, jrRS);
                JasperViewer jrviewer = new JasperViewer(jasperPrint, false);
                jrviewer.setVisible(true);
            }

            //caso queira usar o parâmetro  lido anteriormente no sql
            //String SQL = "SELECT codigo, nome, registro from cliente where codigo = "+codigo+" order by codigo";
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbMarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton rbMarca;
    private javax.swing.JRadioButton rbTodos;
    // End of variables declaration//GEN-END:variables
}
